#!/bin/bash
su - db2inst1 << 'EOF'
db2 connect to BLUDB
db2 "SELECT INSTALLATION2_ID, PROFILE_ID, COUNT(1) as CNT FROM EDC_INST1.OMNIO_DB_INSTALLATION2_PROFILES GROUP BY INSTALLATION2_ID, PROFILE_ID HAVING COUNT(1) > 1"
db2 terminate
EOF

# Made with Bob
